### ISSUE TITLE
Need help compiling this with aot enabled.

### ISSUE THREAD

**Issue by sumeet70** [giovannicandido/angular-http-interceptor#15]
Any ideas how to compile this with ng build --prod.

I get the following error, when I add an import (InterceptorModule.withInterceptors([...])):

ERROR in Error encountered resolving symbol values statically. Calling function 'InterceptorModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule 

Here is my setup:
"dependencies": {
    "@angular/animations": "4.2.5",
    "@angular/common": "4.2.5",
    "@angular/compiler": "4.2.5",
    "@angular/core": "4.2.5",
    "@angular/forms": "4.2.5",
    "@angular/http": "4.2.5",
    "@angular/platform-browser": "^4.2.5",
    "@angular/platform-browser-dynamic": "4.2.5",
    "@angular/platform-server": "4.2.5",
    "@angular/router": "4.2.5",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.20",
    "@ngtools/webpack": "^1.5.0",
    "@types/lodash": "^4.14.52",
    "angular-http-interceptor": "^1.0.2",
    "angular2-uuid": "^1.1.1",
    "core-js": "^2.4.1",
    "lodash": "^4.17.4",
    "mdi": "^1.8.36",
    "ng-http-interceptor": "^3.1.1",
    "ng2-dragula": "^1.3.1",
    "rxjs": "^5.4.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.8.11"
  },
  "devDependencies": {
    "@angular/cli": "^1.2.0",
    "@angular/compiler-cli": "4.2.5",
    "typescript": "^2.4.1",
    "webpack": "^3.0.0"
  }

**Comment by giovannicandido** [comment]
Hi,
Strange, there must be some change in angular, You could use the alternate syntax, while I investigate:

```
imports: [
InterceptorModule
],
providers: [
   {
      provide: Interceptor,
      useClass: CustomInterceptor,
      multi: true
    }
]
```

I will check the code in `RouterModule.forRoot()` to see if my has something not allowed, but it basically returns a ModuleWithProviders.

**Comment by tytskyi** [comment]
hi @giovannicandido i am not user of your library, just wanted to give a tip: yes `InterceptorModule.withInterceptors` has something not allowed. Such methods should be simple `return` statement with no logic, no conditions. 

You mentioned `RouterModule.forRoot()` which is very good example to study from. See how `config` is registered as `ROUTER_CONFIGURATION` and then `ROUTER_CONFIGURATION` is used as a dependency for `LocationStrategy`.

**Comment by giovannicandido** [comment]
@tytskyi Thank you for your tip. 

Problem is, my API is Lazy, in the sense that I force each declaration of a interceptor to be `multi: true` and to have the correct type, so the developer does'nt need to worry about that. This is done in a map operation. That way the syntax:

```
InterceptorModule.withInterceptors([InterceptorClass])
InterceptorModule.withInterceptors([{ provide: Interceptor, useClass: InterceptorClass }])
InterceptorModule.withInterceptors([{ provide: Interceptor, useExisting: InterceptorClass }])
InterceptorModule.withInterceptors([{ provide: Interceptor, useValue: interceptorObject }])
```

Are all valid.

I will check how `ROUTER_CONFIGURATION` is used as a dependecy for LocationStrategy, this should do the trick. Anyway I think some backwards compatibility break could be necessary.

**Comment by giovannicandido** [comment]
@sumeet70 Did the alternate syntax helped? I test locally

**Comment by giovannicandido** [comment]
New 2.0 version fully compatible with AOT and Angular 5
